# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qst_lable = QtWidgets.QLabel(self.centralwidget)
        self.qst_lable.setGeometry(QtCore.QRect(0, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.qst_lable.setFont(font)
        self.qst_lable.setObjectName("qst_lable")
        self.question_entry = QtWidgets.QTextEdit(self.centralwidget)
        self.question_entry.setGeometry(QtCore.QRect(60, 20, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono PS [UKWN]")
        font.setPointSize(14)
        self.question_entry.setFont(font)
        self.question_entry.setObjectName("question_entry")
        self.opt_radio_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_radio_1.setGeometry(QtCore.QRect(30, 150, 21, 31))
        self.opt_radio_1.setObjectName("opt_radio_1")
        self.opt_radio_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_radio_2.setGeometry(QtCore.QRect(30, 210, 21, 31))
        self.opt_radio_2.setText("")
        self.opt_radio_2.setObjectName("opt_radio_2")
        self.opt_radio_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_radio_3.setGeometry(QtCore.QRect(30, 270, 21, 31))
        self.opt_radio_3.setText("")
        self.opt_radio_3.setObjectName("opt_radio_3")
        self.opt_radio_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_radio_4.setGeometry(QtCore.QRect(30, 330, 21, 31))
        self.opt_radio_4.setText("")
        self.opt_radio_4.setObjectName("opt_radio_4")
        self.opt_entry_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.opt_entry_1.setGeometry(QtCore.QRect(60, 150, 441, 31))
        self.opt_entry_1.setObjectName("opt_entry_1")
        self.opt_entry_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.opt_entry_2.setGeometry(QtCore.QRect(60, 210, 441, 31))
        self.opt_entry_2.setObjectName("opt_entry_2")
        self.opt_entry_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.opt_entry_3.setGeometry(QtCore.QRect(60, 270, 441, 31))
        self.opt_entry_3.setObjectName("opt_entry_3")
        self.opt_entry_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.opt_entry_4.setGeometry(QtCore.QRect(60, 330, 441, 31))
        self.opt_entry_4.setObjectName("opt_entry_4")
        self.done_button = QtWidgets.QPushButton(self.centralwidget)
        self.done_button.setEnabled(True)
        self.done_button.setGeometry(QtCore.QRect(770, 470, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_button.setFont(font)
        self.done_button.setMouseTracking(False)
        self.done_button.setObjectName("done_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(650, 470, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(530, 470, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qst_lable.setText(_translate("MainWindow", "Q.No"))
        self.opt_radio_1.setText(_translate("MainWindow", " "))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.back_button.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
